# Generated by Django 4.2.19 on 2025-03-13 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cla", "0005_alter_item_image_borrowrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="borrowrequest",
            name="reason",
            field=models.CharField(default="N/A", max_length=255),
        ),
    ]
