# Generated by Django 4.2.19 on 2025-03-20 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cla', '0006_borrowrequest_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='uploaded_images',
        ),
    ]
