# Generated by Django 4.2.19 on 2025-03-25 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cla', '0009_alter_item_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowrequest',
            name='borrow_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='borrowrequest',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
