# Generated by Django 4.2.19 on 2025-03-25 21:02

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cla', '0010_borrowrequest_borrow_date_borrowrequest_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowrequest',
            name='borrow_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='borrowrequest',
            name='due_date',
            field=models.DateField(default=datetime.date(2025, 4, 1)),
        ),
    ]
