# Generated by Django 4.2.19 on 2025-03-28 21:55

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cla', '0011_alter_borrowrequest_borrow_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='access_requests',
            field=models.ManyToManyField(blank=True, related_name='requested_collections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='borrowrequest',
            name='due_date',
            field=models.DateField(default=datetime.date(2025, 4, 4)),
        ),
    ]
