# Generated by Django 4.2.19 on 2025-03-29 06:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cla', '0012_collection_access_requests_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowrequest',
            name='due_date',
            field=models.DateField(default=datetime.date(2025, 4, 5)),
        ),
    ]
