# Generated by Django 4.2.19 on 2025-04-06 16:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cla', '0016_alter_borrowrequest_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowrequest',
            name='due_date',
            field=models.DateField(default=datetime.date(2025, 4, 13)),
        ),
    ]
