# Generated by Django 4.2.19 on 2025-04-06 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cla', '0017_alter_borrowrequest_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowrequest',
            name='borrow_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='borrowrequest',
            name='due_date',
            field=models.DateField(),
        ),
    ]
