# Generated by Django 4.2.19 on 2025-04-10 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cla', '0018_alter_borrowrequest_borrow_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('checked_in', 'Checked In'), ('in_use', 'In Use'), ('in_repair', 'In Repair'), ('reserved', 'Reserved'), ('lost', 'Lost'), ('on_hold', 'On Hold')], default='checked_in', max_length=20),
        ),
    ]
